### ISSUE TITLE
add intellisense 

### ISSUE THREAD

**Issue by ignatandrei** [hermanussen/JsonByExampleGenerator#1]
Please add this header

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

and for the classes the 

    [GeneratedCode("...", "...")]
    [CompilerGenerated]

to have intellisense

**Comment by hermanussen** [comment]
Thank you!

This should be fixed in the new version: https://www.nuget.org/packages/JsonByExampleGenerator/0.7.0

Can you please check if that works for you?

**Comment by ignatandrei** [comment]
Unfortunately, no. Let's wait for the new version of VS that will show the code ... Thanks !
