### ISSUE TITLE
namespace should be the default assembly name

### ISSUE THREAD

**Issue by ignatandrei** [hermanussen/JsonByExampleGenerator#4]
IF I put the  code in 

C:\test2\JsonByExampleGenerator

the namespace generated by the JsonByExampleGenerator.Example.csroj will be

namespace JsonByExampleGenerator.Example.Json.C.Test2.JsonByExampleGenerator.JsonByExampleGeneratorExample.Products

Please put just the 

namespace JsonByExampleGenerator.Example

**Comment by ignatandrei** [comment]
?

**Comment by hermanussen** [comment]
Well, I may have "overengineered" it a bit. I wanted to prevent any conflicts if you have, e.g.:
```
- ProjectName
 - Folder1
  - example.json
 - Folder2
  - example.json
```

For some reason, in your case, it's using absolute paths for determining namespaces.

I think I'm just going to make it simpler and either report an error if this results in conflicts or add numbers when there are conflicts (Example, Example2, Example3, etc.).

**Comment by ignatandrei** [comment]
Ok
