### ISSUE TITLE
Problem with VS2019

### ISSUE THREAD

**Issue by MBurtsev** [hermanussen/JsonByExampleGenerator#6]
Hey,

I am trying to use a generator and VS is highlighting errors, but the application compiles and runs.
![image](https://user-images.githubusercontent.com/41398/146213572-31620a68-bb8e-41e9-b93a-3810972bb187.png)

**Comment by hermanussen** [comment]
Hi Maksim.

Indeed, the Visual Studio tooling is sometimes lacking in this regard. I think it got better over the different revisions in VS2019 and I haven't tried VS2022 yet.

I suggest updating Visual Studio and seeing if that helps. But I can't really help with this issue.

Thanks for reaching out!

**Comment by MBurtsev** [comment]
Thank you
I'm new to this question please tell me is it supported to debug the generated code?

**Comment by MBurtsev** [comment]
Found example https://github.com/stevetalkscode/DebugSourceGenWithVs2019
