### ISSUE TITLE
Feature Idea - Inline Json to Poco Object/Config

### ISSUE THREAD

**Issue by jakenuts** [hermanussen/JsonByExampleGenerator#7]
What if, you could define json inline in code (or wrapped in an attribute or class) and have that available as an object at runtime? That would be sorta cool, would reduce the noise in fluent builders and such.

**Comment by hermanussen** [comment]
Hi James,

Seems like a pretty good idea to me. I usually prefer putting the json in a separate file, but I can see having it as a constant in your code would be a useful option. An attribute could be used to indicate to the generator to pick it up.

I'll try and make a change soon.

Thanks for reaching out!

Robin

**Comment by hermanussen** [comment]
@jakenuts 

Done. It's in version 0.9.0. Usage instructions here: https://github.com/hermanussen/JsonByExampleGenerator#use-a-constant-string-with-json-data-in-code-to-generate-classes
