### ISSUE TITLE
Remove Microsoft.CodeAnalysis.CSharp.Workspaces 

### ISSUE THREAD

**Issue by jjhayter** [hermanussen/JsonByExampleGenerator#9]
Suggestion to make <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.2.0" /> a private asset to avoid nuget errors like below:

`NU1605: Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Workspaces from 4.2.0 to 3.8.0. Reference the package directly from the project to select a different version. `

NuGetizer is already setup this way.

**Comment by hermanussen** [comment]
Thanks. I'll look into it soon.

**Comment by hermanussen** [comment]
Should be fixed now in version 0.10.0
